dist: xenial
matrix:
  include:
    - language: python
      python:
        - "3.7"
      install:
        - "pip install pipenv"
        - "pipenv sync --dev"
      script:
        - pipenv run python manage.py test --settings=core.settings.test
        - pipenv run flake8 || true  # Enable flake8 linting as a dry-run

    - language: node_js
      node_js:
        - "10.15.3"
      before_install:
        - cd frontend
      install:
        - yarn
      script:
        - yarn lint
        - yarn test
