version: "3"

services:
  db:
    image: postgres:11.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.docker
  client:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data:Z
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
volumes:
  data:
