version: '3'

services:
  db:
    image: postgres:11.3-alpine
    volumes:
      - data:/var/lib/postgresql/data/
  app:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  data:
