# Generated by Django 2.2.1 on 2019-06-04 22:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('last_four_ssn', models.CharField(max_length=4, verbose_name='Last 4 of SSN')),
                ('pp_id', models.CharField(max_length=200, verbose_name='Prevention Point ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mtf', 'Mtf'), ('ftm', 'Ftm'), ('gender queer', 'Gender Queer'), ('other', 'Other')], max_length=12)),
                ('race', models.CharField(choices=[('black (african american)', 'Black (African American)'), ('white (caucasian)', 'White (Caucasian)'), ('asian pi', 'Asian Pi'), ('native american', 'Native American'), ('latino', 'Latino'), ('other', 'Other')], max_length=24)),
                ('date_of_birth', models.DateField()),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_klass_name', models.CharField(default='NotSet', max_length=100)),
                ('available', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Program')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('ARRIVED', 'arrived'), ('CALLED', 'called'), ('SEEN', 'seen'), ('LEFT', 'left')], max_length=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEventData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.ServiceEvent')),
            ],
        ),
        migrations.CreateModel(
            name='UrineDrugScreen',
            fields=[
                ('serviceeventdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ServiceEventData')),
                ('date_of_test', models.DateField()),
                ('uds_temp', models.CharField(max_length=100, verbose_name='Urine Temperature')),
                ('pregnancy_test', models.BooleanField(default=False)),
                ('opiates', models.BooleanField(default=False)),
                ('fentanyl', models.BooleanField(default=False)),
                ('bup', models.BooleanField(default=False, verbose_name='Buprenorphine')),
                ('coc', models.BooleanField(default=False, verbose_name='Cocaine')),
                ('amp', models.BooleanField(default=False, verbose_name='Amphetamine')),
                ('m_amp', models.BooleanField(default=False, verbose_name='Methamphetamine')),
                ('thc', models.BooleanField(default=False, verbose_name='THC')),
                ('mtd', models.BooleanField(default=False, verbose_name='Methadone')),
                ('pcp', models.BooleanField(default=False, verbose_name='PCP')),
                ('bar', models.BooleanField(default=False, verbose_name='Barbiturates')),
                ('bzo', models.BooleanField(default=False, verbose_name='Benzodiazepines')),
                ('tca', models.BooleanField(default=False, verbose_name='Tricyclic Antidepressants')),
                ('oxy', models.BooleanField(default=False, verbose_name='Oxycodone')),
            ],
            bases=('core.serviceeventdata',),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Visit'),
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_delivery', models.CharField(max_length=100)),
                ('medication_name', models.CharField(max_length=100)),
                ('ingestion_frequency', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='CaseManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_seen', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='BehavioralHealthNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_timestamp', models.DateTimeField()),
                ('behavior_note', models.TextField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_timestamp', models.DateTimeField()),
                ('crs_timestamp', models.DateTimeField()),
                ('crs_seen', models.BooleanField(default=False)),
                ('cm_timestamp', models.DateTimeField()),
                ('cm_seen', models.BooleanField(default=False)),
                ('hcv_status', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Participant')),
            ],
        ),
    ]
