# Generated by Django 2.2.13 on 2020-08-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='sep_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
