# Generated by Django 2.2.13 on 2021-02-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='sep_id',
            field=models.CharField(db_index=True, max_length=16, null=True, unique=True),
        ),
    ]
