# Generated by Django 2.2.13 on 2020-08-05 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Form')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Program')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Question')),
            ],
        ),
    ]
