# Generated by Django 2.2.13 on 2020-08-03 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('bool', 'Bool'), ('char', 'Char'), ('datetime', 'Datetime'), ('int', 'Int'), ('varchar', 'Varchar'), ('varchar(255)', 'Varchar(255)')], max_length=24)),
                ('active', models.BooleanField(default=True)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Form')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Program')),
            ],
        ),
    ]
