# Generated by Django 2.2.13 on 2021-02-23 00:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(choices=[('heroin_only', 'Heroin_Only'), ('heroin_and_cocaine', 'Heroin_And_Cocaine'), ('cocaine', 'Cocaine'), ('fentanyl', 'Fentanyl'), ('crack', 'Crack'), ('amphetamines_speed_crystalMeth_ice', 'Amphetamines_Speed_Crystalmeth_Ice'), ('hormones', 'Hormones'), ('steroids', 'Steroids'), ('silicone', 'Silicone'), ('botox', 'Botox'), ('other', 'Other')], max_length=11, verbose_name='Drug injected most often')),
            ],
        ),
        migrations.CreateModel(
            name='SepEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('zip_code', models.CharField(max_length=5, verbose_name='Zip Code')),
                ('housing', models.CharField(choices=[('permanent_housing', 'Permanent_Housing'), ('temporarily_housed', 'Temporarily_Housed'), ('shelter', 'Shelter'), ('street', 'Street'), ('at_risk_for_homelessness', 'At_Risk_For_Homelessness')], max_length=5, verbose_name='Current Housing Situation')),
                ('in_treatment', models.BooleanField(default=False, verbose_name='In Treatment')),
                ('treatment_type', models.CharField(choices=[('methadone', 'Methadone'), ('suboxone', 'Suboxone'), ('vivitrol', 'Vivitrol'), ('IOP', 'Iop'), ('Recovery House', 'Recovery House')], max_length=5, null=True, verbose_name='Type of Drug Treatment')),
                ('health_insurance', models.CharField(choices=[('Medicare', 'Medicare'), ('Medicaid', 'Medicaid'), ('No', 'No'), ('Other', 'Other')], max_length=4, verbose_name='Do they have health insurance')),
                ('health_insurance_other', models.CharField(max_length=100, null=True, verbose_name='Indicate Health Insurance')),
                ('hep_c_test', models.BooleanField(default=False, verbose_name='Tested for hepatitis C')),
                ('hep_c_test_date', models.DateField(null=True)),
                ('hiv_test', models.BooleanField(default=False, verbose_name='Tested for HIV')),
                ('hiv_test_date', models.DateField(null=True)),
                ('narcan', models.BooleanField(default=False, verbose_name='Do you have Narcan today')),
                ('harm_reduction_counseling', models.BooleanField(default=False, verbose_name='Received Harm Reduction Counseling')),
                ('left_with_narcan', models.BooleanField(default=False, verbose_name='Participant left with Narcan')),
                ('overdose_prevention', models.BooleanField(default=False, verbose_name='Received Overdose Prevention Counseling')),
                ('mobile_site_schedule', models.BooleanField(default=False, verbose_name='Participant left with mobile site schedule')),
                ('referred_to_testing', models.BooleanField(default=False, verbose_name='Referred to HIV or HCV testing')),
                ('drug_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DrugMatrix')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Participant')),
            ],
        ),
    ]
