# Generated by Django 2.2.9 on 2020-02-16 19:13

import core.models.visit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191026_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='urgency',
            field=models.CharField(choices=[('_1', 1), ('_2', 2), ('_3', 3), ('_4', 4), ('_5', 5)], default=core.models.visit.UrgencyLevel(1), max_length=20),
        ),
    ]
