# Generated by Django 2.2 on 2019-04-30 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('ARRIVED', 'arrived'), ('CALLED', 'called'), ('SEEN', 'seen'), ('LEFT', 'left')], max_length=10)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Visit')),
            ],
        ),
    ]
