# Generated by Django 2.2.13 on 2021-02-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210201_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='maiden_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name="Mother's Maiden Name"),
        ),
    ]
