# Generated by Django 2.2.13 on 2021-02-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210201_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='sep_id',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
    ]
