# Generated by Django 2.2.10 on 2020-05-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200216_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pp_id',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Prevention Point ID'),
        ),
    ]
