# Generated by Django 2.2.1 on 2019-05-22 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_serviceevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urinedrugscreen',
            name='id',
        ),
        migrations.AddField(
            model_name='urinedrugscreen',
            name='serviceevent_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ServiceEvent'),
            preserve_default=False,
        ),
    ]
