# Generated by Django 2.2.13 on 2021-02-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210201_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(db_index=True),
        ),
    ]
