# Generated by Django 2.2.2 on 2019-07-03 00:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_program_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontDeskEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ARRIVED', 'arrived'), ('SEEN', 'seen'), ('LEFT', 'left'), ('STEPPED_OUT', 'stepped_out'), ('CAME_BACK', 'came_back')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Visit')),
            ],
        ),
        migrations.RemoveField(
            model_name='hcvnotes',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='hcvnotes',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='serviceevent',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cm_employee',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='crs_employee',
        ),
        migrations.RemoveField(
            model_name='behavioralhealthnotes',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeRole',
        ),
        migrations.DeleteModel(
            name='HCVNotes',
        ),
        migrations.DeleteModel(
            name='ServiceEvent',
        ),
    ]
