# Generated by Django 2.2.13 on 2020-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200929_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='maiden_name',
            field=models.CharField(max_length=100, null=True, verbose_name="Mother's Maiden Name"),
        ),
    ]
