# Generated by Django 2.2.13 on 2020-10-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_participant_maiden_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
