# Generated by Django 2.2.13 on 2020-10-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201014_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BehavioralHealthNotes',
            new_name='BehavioralHealthNote',
        ),
        migrations.RenameModel(
            old_name='HCVNotes',
            new_name='HCVNote',
        ),
    ]
