# Generated by Django 2.2.13 on 2020-10-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201020_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sep_Data',
            new_name='SepData',
        ),
    ]
