# Generated by Django 2.2.2 on 2019-10-03 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_program_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='program',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='program',
        ),
        migrations.AddField(
            model_name='visit',
            name='urgency',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.CreateModel(
            name='ProgramServiceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Program')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Program')),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='program_service_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ProgramServiceMap'),
        ),
    ]
