# Generated by Django 2.2.2 on 2019-08-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_programavailability'),
        ('core', '0008_program_is_closed'),
    ]

    operations = [
    ]
