# Generated by Django 2.2.13 on 2020-12-05 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201020_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Insurer'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='maiden_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Mother's Maiden Name"),
        ),
    ]
