# Generated by Django 2.2.13 on 2020-12-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201020_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
