# Generated by Django 2.2.13 on 2020-11-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201020_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='sep_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
