# Generated by Django 2.2.2 on 2019-10-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20190823_2213'),
        ('core', '0009_programavailability'),
    ]

    operations = [
    ]
