# Generated by Django 2.2.13 on 2020-12-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_program_has_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='has_queue',
            field=models.BooleanField(default=True),
        ),
    ]
