# Generated by Django 2.2.2 on 2019-09-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_visit_urgency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='program',
        ),
    ]
