# Generated by Django 2.2.13 on 2021-01-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201216_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepdata',
            name='exchanged_for',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
