# Generated by Django 2.2.13 on 2021-01-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201216_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='Concise Descriptive Identifier'),
        ),
    ]
