apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prevention-point.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prevention-point.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prevention-point.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "prevention-point.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ .Release.Name }}-postgresql-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-postgresql-data
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "app"
            - "db"
      containers:
        {{- with .Values.backend }}
        - name: {{ $.Chart.Name }}-backend
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: core.settings.docker
          livenessProbe:
            httpGet:
              path: /
              port: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
        {{- end }}
        {{- with .Values.frontend }}
        - name: {{ $.Chart.Name }}-frontend
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
        {{- end }}
        {{- with .Values.database }}
        - name: {{ $.Chart.Name }}-database
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: {{ $.Release.Name }}-postgresql-data
              mountPath: /var/lib/postgresql/data
              subPath: postgresql-data
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
