apiVersion: v1
kind: Service
metadata:
  name: {{ include "prevention-point.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prevention-point.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: frontend-http
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: backend-http
  selector:
    {{- include "prevention-point.selectorLabels" . | nindent 4 }}
