#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e
cd "$(dirname "$0")/.."


script/bootstrap

echo
echo "==> Starting containers with docker-compose…"
docker-compose up -d --build

echo 
echo "==> Initialize static assets"
docker-compose exec app python manage.py collectstatic

echo
echo "==> App is now ready to go!"
echo "    *Open http://localhost:8080"
echo
