from core.tests.visits import *
from core.tests.front_desk_events import *
from core.tests.participants import *
from core.tests.users import *
from core.tests.groups import *
from core.tests.services import *
from core.tests.programs import *
from core.tests.queue import *
from core.tests.program_availability  import *
from core.tests.insurers import *
from core.tests.site import *
